# -*- coding: utf-8 -*-
"""lista3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkzNKy_cUDoK7ahrL76181wmvz9UtX3s

# Lista 03 - Análise Exploratória de Dados

Continuando da última lista, vamos agora realizar um pouco dos passos da análise exploratória de dados. Em particular, vamos passar pelos passos de:

1. Carregamento dos dados
1. Limpeza dos dados
1. Análise exploratória com gráficos e estatísticas simples

## Imports Básicos

As células abaixo apenas configuram nosso notebook para ficar mais parecido com os das aulas
"""

from numpy.testing import assert_almost_equal
from numpy.testing import assert_equal

from numpy.testing import assert_array_almost_equal
from numpy.testing import assert_array_equal

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

plt.rcParams['figure.figsize']  = (16, 10)
plt.rcParams['axes.labelsize']  = 20
plt.rcParams['axes.titlesize']  = 20
plt.rcParams['legend.fontsize'] = 20
plt.rcParams['xtick.labelsize'] = 20
plt.rcParams['ytick.labelsize'] = 20
plt.rcParams['lines.linewidth'] = 4

plt.ion()
plt.style.use('seaborn-colorblind')

# ==============================================================================
# O CÓDIGO DO TUTORIAL FOI MOVIDO PARA O BLOCO if __name__ == '__main__'
# AO FINAL DO ARQUIVO PARA NÃO SER EXECUTADO DURANTE TESTES AUTOMATIZADOS.
# O TEXTO EXPLICATIVO FOI MANTIDO AQUI PARA FINS DE LEITURA.
# ==============================================================================

"""## Notas dos Alunos (Tutorial)

Como falamos na última lista, em muitos cenários do mundo real, os dados são carregados de fontes como arquivos. Vamos substituir o DataFrame das notas dos alunos pelo conteúdo de um arquivo de texto.

O método `read_csv` do `DataFrame` é usado para carregar dados de arquivos de texto. Como você pode ver no código de exemplo, você pode especificar opções como o delimitador de coluna e qual linha (se houver) contém cabeçalhos de coluna (neste caso, o delimitador é uma vírgula e a primeira linha contém os nomes das colunas).

Além do mais, a chamada `head` imprime as primeiras cinco linhas da nossa tabela.

### Dados Faltantes

Um dos problemas mais comuns com os quais os cientistas de dados precisam lidar são dados incompletos ou ausentes. Como podemos saber que o DataFrame contém valores ausentes? Você pode usar o método `isnull` para tal tarefa.

Obseve como a última linha falta com o número de horas estudadas. Nas dúas últimas, faltam as notas. Caso você deseja saber a quantidade de dados faltantes, basta somar os `True`s da tabela acima. Aqui é importante saber que Python tratta `True` de forma similar ao número 1. Portanto, basta você somar a tabela inteira para pegar tal quantidade de dados faltantes.

Lembrando que a chamada `iloc` pega uma linha com base no número da mesma, vamos observar a última linha da tabela de dados. Observe como os valores faltantes viram `NaN`s. Além do mais, lembre-se que podemos indexar de trás para frente com o -1. -1 é a última linha, -2 a penúltima. Para entender a lógica, em um vetor de tamanho `n`, `n-1` é o último elemento. Indexar `-1` indica `n-1`.

Agora que encontramos os valores faltantes, o que podemos fazer a respeito deles?

#### fillna

Uma abordagem comum é imputar valores de substituição. Por exemplo, se o número de horas de estudo está faltando, podemos simplesmente supor que o aluno estudou por um período médio de tempo e substituir o valor faltante com as horas de estudo médias. Para fazer isso, podemos usar o método fillna, como este:

Observe que a última linha foi alterada! Porém, o DataFrame original não foi.

Para alterar, podemos trocar a coluna. Abaixo faço tal operação em uma cópia dos dados. Realizei tal escolha apenas para não mudar a tabela original.

Observe como não mudamos nada das notas. O `fillna` pode receber uma série indexada para alterar várias colunas. Primeiramente, observe como a chamada `mean` pega a média de todas as colunas.

O `fillna` então vai pegar o índice dessa série, o nome da coluna, e utilizar como chave para quais colunas imputar. O valor da série indica o valor que será imputado. Observe como os novos dados abaixo estão sem NaNs.

#### dropna

Outra opção é simplesmente remover todas as linhas com dados faltantes. Para tal, fazemos uso da chamada `dropna`.

Observe como o novo DataFrame tem duas linhas a menos do que o anterior. A escolha de como limpar dados faltantes depende do tipo de análise que você vai realizar. Aqui, vamos seguir com o drop no `df`.

### Explorando Dados

... (O restante do texto do tutorial é omitido por brevidade, mas a ideia é que ele permaneça no seu arquivo) ...

"""

"""## Exercícios (Flight Data)

Eu espero que o tutorial acima tenha sido uma boa revisão de análise exploratória de dados. Agora é com você! Nesta lista, você explorará um conjunto de dados do mundo real contendo dados de voos do Departamento de Transporte dos EUA.

Vamos começar carregando e visualizando os dados.
"""

df_flights = pd.read_csv('https://raw.githubusercontent.com/icd-ufmg/icd-ufmg.github.io/master/listas/l3/flights.csv')

"""O conjunto de dados contém observações de voos domésticos dos EUA em 2013 e consiste nos seguintes campos:
* Ano: o ano do voo (todos os registros são de 2013)
* Mês: o mês do voo
* Dia do mês: o dia do mês em que o voo partiu
* DayOfWeek: o dia da semana em que o voo partiu - de 1 (segunda-feira) a 7 (domingo)
* Transportadora: a abreviatura de duas letras da companhia aérea.
* OriginAirportID: Um identificador numérico exclusivo para o aeroporto de partida
* Nome do aeroporto de origem: o nome completo do aeroporto de partida
* OriginCity: a cidade do aeroporto de partida
* Estado de origem: o estado do aeroporto de partida
* DestAirportID: Um identificador numérico único para o aeroporto de destino
* DestAirportName: o nome completo do aeroporto de destino
* DestCity: a cidade do aeroporto de destino
* DestState: o estado do aeroporto de destino
* CRSDepTime: a hora de partida programada
* DepDelay: o número de minutos de atraso na partida (o voo que saiu antes do horário tem um valor negativo)
* DelDelay15: Um indicador binário de que a partida foi atrasada por mais de 15 minutos (e, portanto, considerada "atrasada")
* CRSArrTime: a hora de chegada programada
* ArrDelay: o número de minutos de atraso na chegada (o voo que chegou antes do horário tem um valor negativo)
* ArrDelay15: Um indicador binário de que a chegada foi atrasada em mais de 15 minutos (e, portanto, considerada "atrasada")
* Cancelado: um indicador binário de que o voo foi cancelado
"""

### Exercício 1

#Conte a quantidade de dados faltantes na tabela. Isto é, em TODAS as células. O método retorna apenas um número.
###
def count_missing(df) -> int:
    result = df.isnull().sum().sum()
    return int(result)

### Exercício 2

#Crie um novo DataFrame sem as linhas com dados faltantes
###
def drop_missing(df):
    new_df = df.dropna()
    return new_df

### Exercício 3

#Retorne a mediana de TODAS as colunas numéricas do DataFrame
###
def all_median(df):
    result = df.median()
    return result

### Exercício 4

#Quais são os atrasos médios (médios) de partida e chegada? Retorne uma tupla.
###
def delay(df) -> tuple:
    # O método mean() já ignora valores NaN por padrão
    atr_p = df['DepDelay'].mean()
    atr_c = df['ArrDelay'].mean()
    return (atr_p, atr_c)

### Exercício 5

#Indique qual rota tem o maior tempo de voo em MÉDIA. Use a coluna OriginAirportName e DestinationAirportName. Retorne uma tupla `(OriginAirportName, DestinationAirportName)`. Lembre-se de não considerar voos cancelados!
###
def high_delay(df):
    # Filtra voos válidos e cria uma cópia para evitar avisos
    good_flights = df.query('Cancelled == 0').dropna(subset=['CRSArrTime', 'CRSDepTime', 'OriginAirportName', 'DestAirportName'])
    good = good_flights.copy()

    # Converte HHMM para minutos desde a meia-noite para calcular a duração
    dep_hours = good['CRSDepTime'] // 100
    dep_mins = good['CRSDepTime'] % 100
    arr_hours = good['CRSArrTime'] // 100
    arr_mins = good['CRSArrTime'] % 100

    dep_total_mins = dep_hours * 60 + dep_mins
    arr_total_mins = arr_hours * 60 + arr_mins

    # Calcula a duração e corrige para voos que cruzam a meia-noite
    duration = arr_total_mins - dep_total_mins
    duration[duration < 0] += 1440  # Adiciona 24 horas em minutos
    good['FlightDuration'] = duration

    # Agrupa por rota, calcula a média e encontra a rota com o maior valor
    avg_duration_by_route = good.groupby(['OriginAirportName', 'DestAirportName'])['FlightDuration'].mean()
    longest_route = avg_duration_by_route.idxmax()
    return longest_route

### Exercício 6

#Faça um boxplot dos atrasos de saída por dia da semana!
#
#1. Dica, use `grid=False, showfliers=False` para o plot ficar mais limpo
#
#*Saída esperada*
#
#![](https://raw.githubusercontent.com/icd-ufmg/icd-ufmg.github.io/master/listas/l3/plot1.png)
###

# O CÓDIGO DE PLOTAGEM ESTÁ NO BLOCO if __name__ == '__main__'

### Exercício 7

#Correlacione o atraso de saída com o atraso de chegada!
#
#1. Dica, remova os voos cancelados
#
#*Saída esperada*
#
#![](https://raw.githubusercontent.com/icd-ufmg/icd-ufmg.github.io/master/listas/l3/plot2.png)
###

# O CÓDIGO DE PLOTAGEM ESTÁ NO BLOCO if __name__ == '__main__'


# ==============================================================================
# BLOCO PRINCIPAL
# Este código só roda quando o script é executado diretamente.
# ==============================================================================
if __name__ == '__main__':
    # --- Demonstração do Tutorial (Notas dos Alunos) ---
    print("--- INÍCIO DA DEMONSTRAÇÃO DO TUTORIAL ---")
    df_grades = pd.read_csv('https://raw.githubusercontent.com/icd-ufmg/icd-ufmg.github.io/master/listas/l3/grades.csv', sep=',', header=0)
    print("Primeiras 5 linhas do DataFrame de notas:")
    print(df_grades.head())
    print("\nVerificando dados faltantes:")
    print(df_grades.isnull().sum())
    # O restante do código do tutorial pode ser colocado aqui para demonstração...
    print("--- FIM DA DEMONSTRAÇÃO DO TUTORIAL ---\n")

    # --- Execução e Teste dos Exercícios (Flight Data) ---
    print("--- INÍCIO DA EXECUÇÃO DOS EXERCÍCIOS ---")
    print("Primeiras 5 linhas do DataFrame de voos:")
    print(df_flights.head())
    
    # Testes dos exercícios (assertions)
    assert_equal(2761, count_missing(df_flights))
    assert_equal(269179, drop_missing(df_flights).shape[0])
    assert_equal(2013, all_median(df_flights)['Year'])
    assert_equal(7, all_median(df_flights)['Month'])
    assert_almost_equal(10.456614371849216, delay(df_flights)[0])
    assert_almost_equal(6.563286883449304, delay(df_flights)[1])
    print("Asserts dos exercícios 1 a 4 passaram com sucesso!")
    
    # Execução do exercício 5
    rota_longa = high_delay(df_flights)
    print(f"\nEx 5: Rota com maior tempo médio de voo: {rota_longa}")

    # Código para plotar o gráfico do Exercício 6
    print("\nGerando gráfico para o Exercício 6...")
    plt.figure()
    df_flights.boxplot(column='DepDelay', by='DayOfWeek', grid=False, showfliers=False)
    plt.title('Atraso na Partida por Dia da Semana')
    plt.suptitle('')  # Remove o título automático
    plt.xlabel('Dia da Semana')
    plt.ylabel('Atraso na Partida (minutos)')

    # Código para plotar o gráfico do Exercício 7
    print("Gerando gráfico para o Exercício 7...")
    df_not_cancelled = df_flights[df_flights['Cancelled'] == 0]
    plt.figure()
    plt.scatter(x=df_not_cancelled['DepDelay'], y=df_not_cancelled['ArrDelay'], alpha=0.5, edgecolors='k', s=20)
    plt.title('Atraso na Chegada vs. Atraso na Partida')
    plt.xlabel('Atraso na Partida (minutos)')
    plt.ylabel('Atraso na Chegada (minutos)')
    plt.grid(True)

    # Exibe todos os gráficos gerados
    print("Exibindo gráficos...")
    plt.show()
    print("--- FIM DA EXECUÇÃO DOS EXERCÍCIOS ---")